gpt-4o-2024-08-06_CoT_v1:
  prompt_template: "gpt-4o-2024-08-06_CoT_v1/prompt.txt"
  fn_completions: "openai_completions"
  completions_kwargs:
    model_name: "gpt-4o-2024-08-06"
    max_tokens: 8192
    temperature: 0.0
    tool_choice:
      type: function
      function:
        name: "generate_detailed_analytic_rubric"
    tools:
      - type: function
        function:
          name: "generate_detailed_analytic_rubric"
          description: "Generate a detailed analytic rubric for evaluating LLM outputs on a given assignment. The rubric should be designed for use by non-expert evaluators, including crowdworkers or other LLMs, who may not have domain-specific knowledge."
          strict: true
          parameters:
            type: "object"
            properties:
              learning_objectives:
                type: "string"
                description: "Clearly define the learning objectives of the assignment, providing context for non-expert evaluators."
              # brainstormed_response:
              #   type: "string"
              #   description: "Provide a very strong solution for the assignment, serving as a reference for evaluators."
              brainstormed_rubric:
                type: "array"
                description: "A list of 2-10 dictionaries, each corresponding to a criterion in the analytic rubric."
                items:
                  type: "object"
                  description: "A criterion for the assignment"
                  properties:
                    criterion:
                      type: "string"
                      description: "Concise, descriptive name of the criterion."
                    weight:
                      type: "integer"
                      description: "A number between 0-100 representing the importance of the criterion."
                    checklist:
                      type: "array"
                      description: "A list of 3-15 specific elements to consider when evaluating this criterion. Each element should contain a detailed description of what to look for, including examples if applicable. Specify whether the example is the only correct answer or one of multiple possible correct answers. Describe the severity or importance of getting this element wrong."
                      items:
                        type: "string"
                  additionalProperties: false
                  required: ["criterion", "weight", "checklist"]
            additionalProperties: false
            required: ["learning_objectives",  "brainstormed_rubric"]
  fn_completion_parser: "json_parser"
  completion_parser_kwargs:
    annotation_key: "brainstormed_rubric"
