claude-2:
  prompt_template: "claude-2/prompt.txt"
  fn_completions: "anthropic_completions"
  completions_kwargs:
    model_name: "claude-2"
    max_tokens_to_sample: 4096
  batch_size: 1
  fn_completion_parser: null

