claude-3-sonnet-20240229:
  prompt_template: "claude-3-sonnet-20240229/prompt.txt"
  fn_completions: "anthropic_completions"
  completions_kwargs:
    model_name: "claude-3-sonnet-20240229"
    max_tokens_to_sample: 4096
    num_procs: 2
  batch_size: 1
  fn_completion_parser: null