gpt-4-turbo-2024-04-09:
  prompt_template: "gpt-4-turbo-2024-04-09/prompt.txt"
  fn_completions: "openai_completions"
  completions_kwargs:
    model_name: "gpt-4-turbo-2024-04-09"
    max_tokens: 4096
    requires_chatml: True
  batch_size: 1
  fn_completion_parser: null