gpt-4o-mini-2024-07-18_CoT_v0:
  prompt_template: "gpt-4o-2024-08-06_CoT_v0/prompt.txt"
  fn_completions: "openai_completions"
  completions_kwargs:
    model_name: "gpt-4o-mini-2024-07-18"
    max_tokens: 8192
    temperature: 0.0
    tool_choice:
      type: function
      function:
        name: "generate_detailed_analytic_rubric"
    tools:
      - type: function
        function:
          name: "generate_detailed_analytic_rubric"
          description: "Generate a detailed analytic rubric for evaluating LLM outputs on a given assignment."
          strict: true
          parameters:
            type: "object"
            properties:
              learning_objectives:
                type: "string"
                description: "Clearly define the learning objectives of the assignment."
              brainstormed_response:
                type: "string"
                description: "Provide a very strong solution for the assignment."
              brainstormed_rubric:
                type: "array"
                description: "A list of 3-6 dictionaries, each corresponding to a criterion in the analytic rubric."
                items:
                  type: "object"
                  description: "A criterion for the assignment"
                  properties:
                    criterion:
                      type: "string"
                      description: "Concise, descriptive name of the criterion."
                    weight:
                      type: "integer"
                      description: "A number between 0-100 representing the importance of the criterion."
                    checklist:
                      type: "array"
                      description: "A list of 5-10 specific questions or points to consider when evaluating this criterion."
                      items:
                        type: "string"
                  additionalProperties: false
                  required: ["criterion", "weight", "checklist"]
            additionalProperties: false
            required: ["learning_objectives", "brainstormed_response", "brainstormed_rubric"]
  fn_completion_parser: "json_parser"
  completion_parser_kwargs:
    annotation_key: null
