chatgpt:
  prompt_template: "chatgpt/prompt.txt"
  fn_completions: "openai_completions"
  completions_kwargs:
    model_name: "gpt-3.5-turbo-0125"
    max_tokens: 4096
  batch_size: 1
  fn_completion_parser: null