gpt4_CoT_v0:
  prompt_template: "gpt4_CoT_v0/prompt.txt"
  fn_completions: "openai_completions"
  completions_kwargs:
    model_name: "gpt-4-turbo-preview"
    max_tokens: 4096
    temperature: 0.3
    function_call:
      name: "generate_detailed_rubric"
    functions:
      - name: "generate_detailed_rubric"
        description: "Generate a detailed rubric for a given assignment."
        parameters:
          type: "object"
          properties:
            clear_goals:
              type: "string"
              description: "The learning objectives of the assignment."
            # final_prompt:
            #   type: "string"
            #   description: "The prompt that defines the assignment for the model."
            criteria:
              type: "object"
              description: "The criteria for the assignment, the keys are the key aspects and the values are thorough lists of checklist questions tailored to the assignment."
              items:
                type: "string"
        "required": ["clear_goals", "criteria"]
  batch_size: 1
  fn_completion_parser: "json_parser"
  completion_parser_kwargs:
    annotation_key: null
