gpt-4o-2024-05-13_CoT_v0:
  prompt_template: "gpt-4o-2024-05-13_CoT_v0/prompt.txt"
  fn_completions: "openai_completions"
  completions_kwargs:
    model_name: "gpt-4o-2024-05-13"
    max_tokens: 4096
    temperature: 0.0
    function_call:
      name: "generate_detailed_rubric"
    functions:
      - name: "generate_detailed_rubric"
        description: "Generate a detailed rubric for a given assignment."
        parameters:
          type: "object"
          properties:
            clear_goals:
              type: "string"
              description: "The learning objectives of the assignment."
            criteria:
              type: "array"
              description: "A list of exactly 5 objects, each object contains one criteria for the assignment and the checklist questions for the criterion."
              items:
                type: "object"
                description: "A criterion for the assignment"
                properties:
                  aspect:
                    type: "string"
                    description: "The key aspect of the criteria."
                  checklist:
                    type: "array"
                    description: "A list of strings. Each string element should be a concrete and detailed question that is tailored to the assignment and should be used to judge the corresponding aspect."
                    items:
                      type: "string"
        "required": ["clear_goals", "criteria"]
  batch_size: 1
  fn_completion_parser: "json_parser"
  completion_parser_kwargs:
    annotation_key: null
